apiVersion: apps/v1
kind: Deployment
metadata:
    name: backend
spec:
    replicas: 1
    selector:
        matchLabels:
            app: backend
    template:
        metadata:
            labels:
                app: backend
        spec:
            containers:
                - image: sergioandresestrada/cloud_backend:0.3
                  name: backend
                  env:
                      - name: AWS_ACCESS_KEY_ID
                        valueFrom:
                            secretKeyRef:
                                name: awscredentials
                                key: AWS_ACCESS_KEY_ID
                      - name: AWS_SECRET_ACCESS_KEY
                        valueFrom:
                            secretKeyRef:
                                name: awscredentials
                                key: AWS_SECRET_ACCESS_KEY
                      - name: SERVER_URL
                        value: "https://backend-sergioandresestrada.cloud.okteto.net"

                      - name: SQS_QUEUE_NAME
                        value: "test.fifo"

                      - name: S3_BUCKET_NAME
                        value: "sergiotfgbucket"

---
apiVersion: v1
kind: Service
metadata:
    name: backend
    annotations:
        dev.okteto.com/auto-ingress: "true"
spec:
    type: ClusterIP
    ports:
        - name: "backend"
          port: 12345
    selector:
        app: backend
